version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands: 
      - cd frontend
      npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build/
  files:
    - '**/*'
